WIP: Re-organizing the FAQ content
cert-manager/website pull request #1060
Opened 2022-08-24 14:38 UTC by wallrj

- [ ] Move the "writing cert-manager" content to the main FAQ page

2022-08-24 15:56 UTC, JoshVanL requested changes

2022-08-24 15:56 UTC, JoshVanL commented on public/_redirects
> +/docs/faq/cluster-resource/  /docs/configuration/
Missing `301!` at the end.

2022-08-25 03:49 UTC, jsoref commented on content/docs/configuration/README.md
> +which are able to sign certificates in response to certificate signing requests.
```suggestion
able to sign certificates in response to certificate signing requests.
```

2022-08-25 03:49 UTC, jsoref commented on content/docs/configuration/README.md
>  read more about `Issuer` and `ClusterIssuer` resources [here](../concepts/issuer.md).
`here` links are considered harmful/inaccessible.

2022-08-25 03:49 UTC, jsoref commented on content/docs/configuration/README.md
>  Both built-in and external issuers are treated the same and are configured similarly.
```suggestion
Built-in and external issuers are treated the same and are configured similarly.
```

2022-08-25 03:49 UTC, jsoref commented on content/docs/configuration/README.md
> +Resource Namespace`. By default, this namespace is `cert-manager` however can be
```suggestion
Resource Namespace`. By default, this namespace is `cert-manager` however it can be
```

2022-08-25 03:49 UTC, jsoref commented on content/docs/faq/README.md
> +used between the words, don't replace it with a space or remove it.
```suggestion
used between the words, don't replace it with a space and don't remove it.
```

2022-08-26 10:09 UTC, maelvls commented
This link should be removed.
![Screenshot from 2022-08-26 12-07-53](https://user-images.githubusercontent.com/2195781/186881327-71b9d9b1-9f18-44c7-89e9-b51168d613c2.png)

2022-08-26 10:31 UTC, wallrj reviewed
Thanks @jsoref  and @JoshVanL 

We've addressed your comments.

2022-08-26 10:31 UTC, wallrj commented on content/docs/configuration/README.md
>  read more about `Issuer` and `ClusterIssuer` resources [here](../concepts/issuer.md).
Done.

2022-08-26 10:31 UTC, wallrj commented on public/_redirects
> +/docs/faq/cluster-resource/  /docs/configuration/
Done.

2022-08-26 10:32 UTC, maelvls commented
It seems like all the changes requested by Josh and Josh have been fixed.

/lgtm

2022-08-26 10:36 UTC, merged