Adding SSA related warnings to the affected versions
cert-manager/website pull request #1091
Opened 2022-10-16 13:37 UTC by sathyanarays

Signed-off-by: Sathyanarayanan Saravanamuthu <sathyanarays@.vmware.com>

## Description
- Added notes for versions 1.7, 1.8, 1.9 and 1.10 to enable SSA in the cluster
- Added a line to mandate SSA enabled while upgrading from 1.6 to 1.7
- - I haven't added this line to other upgrades (1.7 -> 1.8,...). These are not required. For example, if any customer is running version 1.7 successfully, that implicitly means SSA is enabled. So, no special instructions are required.

2022-10-17 09:06 UTC, JoshVanL requested changes
Thanks @sathyanarays!

I think we should also add that the feature gate is required for the v1.8 and v1.9 upgrade docs for completeness.

2022-10-17 09:06 UTC, JoshVanL commented on content/docs/installation/supported-releases.md
> +\*ServerSideApply should be enabled in the cluster
```suggestion
\*ServerSideApply must be enabled in the cluster.

```

2022-10-17 09:06 UTC, JoshVanL commented on content/docs/installation/supported-releases.md
> +\*ServerSideApply should be enabled in the cluster
```suggestion
\*ServerSideApply must be enabled in the cluster.

```

2022-10-17 09:06 UTC, JoshVanL commented on content/docs/installation/upgrading/upgrading-1.6-1.7.md
> +If you have disabled the ServerSideApply feature gate, ensure to enabled them.
```suggestion
If running Kubernetes versions before `v1.22`, the [`ServerSideApply`](https://kubernetes.io/docs/reference/using-api/server-side-apply/) feature gate _must_ be enabled. This beta feature is enabled by default on supported versions before `v1.22`.
```

2022-10-18 04:14 UTC, sathyanarays commented on content/docs/installation/supported-releases.md
> +\*ServerSideApply should be enabled in the cluster
Done!

2022-10-18 14:58 UTC, sathyanarays commented
> Thanks @sathyanarays!
> 
> I think we should also add that the feature gate is required for the v1.8 and v1.9 upgrade docs for completeness.

@JoshVanL made the changes as suggested!

2022-11-01 15:46 UTC, JoshVanL commented
/lgtm
/approve

2022-11-01 15:47 UTC, JoshVanL commented
/ok-to-test

2022-11-01 16:03 UTC, merged