add 404 page
cert-manager/website pull request #1153
Opened 2023-01-12 20:26 UTC by relativelyrehan

Signed-off-by: relativelyrehan <rehan18alam@gmail.com>

Solve #974 

This 404 page can be accessed by going to any unavailable route

### Desktop

<img width="1512" alt="Screenshot 2023-01-13 at 1 53 40 AM" src="https://user-images.githubusercontent.com/48210765/212173356-9dc28097-e530-480f-be01-9745fa3cd278.png">

### Mobile
<img width="366" alt="Screenshot 2023-01-13 at 1 55 18 AM" src="https://user-images.githubusercontent.com/48210765/212173655-c59000ed-96ac-4e6e-85a2-00d8c7fae598.png">

2023-01-13 09:52 UTC, wallrj requested changes
Thanks @relativelyrehan !

It looks great, but the 404 in the 404 image seems to be cropped. 

And do you think we need to make some other change to make this work for clients without Javascript. 

When I visit https://deploy-preview-1153--cert-manager-website.netlify.app/docs/install/verify/ ([a known broken link)](https://github.com/cert-manager/website/pull/1154) it displays the Netlify default 404 page instead.

2023-01-13 10:01 UTC, wallrj commented
See https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling

2023-01-13 12:32 UTC, relativelyrehan commented
@wallrj that 404 image has that design, in which the 404 seems to be cropped. That is intentional design to indicate the idea of a broken page. 

For users without JS, I think it's not an issue as on build all of this will be a static HTML with image url and homepage url, both of them are static sources.

2023-01-13 12:37 UTC, wallrj commented
> @wallrj that 404 image has that design, in which the 404 seems to be cropped. That is intentional design to indicate the idea of a broken page.

It's an interesting idea, but my first reaction was that the image is broken. 
Please use a non cropped image and then I'll be happy to merge this.

2023-01-13 13:00 UTC, relativelyrehan commented
@wallrj I will have a look at the documentation for netlify, because there it doesn't seems to work.

I have one question though, are we using netlify for the production deploy too?

2023-01-13 13:12 UTC, wallrj commented
It might be worth investigating that in a separate PR though. What you've got in this branch is nice and self contained and is a clear improvement which *I think* should work for people who have JavaScript enabled and who are simply clicking around the site.

2023-01-17 17:44 UTC, SgtCoDFish commented on pages/404.jsx
> +            </p>
suggestion:

```suggestion
            <p className="text-base mb-5 lg:mb-14 lg:text-xl max-w-3xl">
                The page you are looking for might have been removed, had its name changed, or be temporarily unavailable.
            </p>
```

2023-01-17 18:49 UTC, wallrj commented
/ok-to-test

2023-01-17 18:59 UTC, wallrj approved these changes
@relativelyrehan It's been pointed out to me that I probably shouldn't be nitpicking on your 404 logo design. This is a great improvement over the default Netlify page.  
Thanks for sorting it out.

/approve
/lgtm

2023-01-17 19:00 UTC, merged

2023-01-17 19:05 UTC, relativelyrehan commented
@wallrj no problem. Thanks for the merge. I also wanted to check with you if there is any open position for a partime paid frontend developer in your org.