Add release notes for 1.11.2->1.11.4
cert-manager/website pull request #1268
Opened 2023-08-07 15:34 UTC by swghosh

Release notes for 1.11.2, 1.11.3, 1.11.4

2023-08-07 15:37 UTC, swghosh commented
/cc @SgtCoDFish @irbekrm @inteon

2023-08-07 16:19 UTC, SgtCoDFish requested changes
Hey, thanks so much for this - this is an awesome PR to receive!

Our syntax parser is quite strict and is complaining about the `<br>` tags - I've added a suggestion for how to fix. Could you do that?

Thanks again!

2023-08-07 16:19 UTC, SgtCoDFish commented on content/docs/release-notes/release-notes-1.11.md
> +
suggestion:
```suggestion
- Bumps Docker libraries to fix vulnerability scan alert for CVE-2023-28840, CVE-2023-28841, CVE-2023-28842 ([#6037](https://github.com/cert-manager/cert-manager/pull/6037), [@irbekrm](https://github.com/irbekrm)) - cert-manager was not actually affected by these CVEs which are all to do with Docker daemon's overlay network.
- Bumps Kube libraries v0.26.0 -> v0.26.4 ([#6038](https://github.com/cert-manager/cert-manager/pull/6038), [@irbekrm](https://github.com/irbekrm)) - this might help with running cert-manager v1.11 on Kubernetes v1.27

```

2023-08-07 18:15 UTC, swghosh commented on content/docs/release-notes/release-notes-1.11.md
> +
Updated :)

2023-08-07 18:16 UTC, swghosh commented
@SgtCoDFish I've updated it, PTAL.
Thanks very much for the review!

2023-08-08 09:12 UTC, SgtCoDFish commented
Looks like there are a few spelling checker issues. I think most of them could be marked as `code` and that'd help it pass!

2023-08-08 10:42 UTC, swghosh commented
@SgtCoDFish fixed the spelling errors now.

```
» npm run check:spelling

> cert-manager.io@2.0.0 check:spelling
> FORCE_COLOR=1 mdspell --report --en-us --ignore-numbers --ignore-acronyms 'content/**/*.md' 'content/**/*.html' '_layouts/*.html' '_includes/*.html' '*.html' '!**/api-docs.md' '!content/*docs/projects/approver-policy/api-reference.md' # Force color output in mdspell. # See https://github.com/lukeapage/node-markdown-spellcheck/issues/36#issuecomment-482649408

>> 1093 files are free from spelling errors
```

2023-08-08 13:09 UTC, SgtCoDFish approved these changes
/lgtm
/approve

Really appreciate this, thank you so much 😁 ❤️

2023-08-08 13:10 UTC, merged