Update install instructions, making them consistent for all sub-projects
cert-manager/website pull request #1449
Opened 2024-03-15 08:10 UTC by inteon

Use a consistent set of installation commands across all installation pages.

2024-03-15 09:17 UTC, wallrj requested changes
1. Seems like unnecessary churn to me. 
2. It introduces the cert-manager version everywhere, giving the false impression (I think) that istio-csr, csi-driver, etc depend on that particular version. As I [already said in another review](https://github.com/cert-manager/website/pull/1439#pullrequestreview-1933998056).
3. I think the goal should be to remove the `helm **upgrade**` instruction from each of the component install pages, because it risks users accidentally upgrading an important existing cert-manager installation and this change does not advance that goal.
4. I don't have time to test all the changes.

Have you tested everything?

2024-06-03 08:08 UTC, inteon commented
@wallrj

I updated the cert-manager instructions for approver-policy and csi-driver-spiffe (replaced `helm install`/ `helm upgrade --install` with `helm upgrade --reuse-values`. I also tested that this works as expected for the approver-policy installation.

2024-06-03 08:49 UTC, inteon commented on content/docs/installation/helm.md
> -#### 2. Update your local Helm chart repository cache:
This section has become redundant.

2024-06-05 10:34 UTC, inteon commented on content/docs/usage/csi-driver-spiffe/installation.md
> +  --reuse-values \
fixed

2024-06-05 10:37 UTC, inteon commented
/approve

2024-06-05 10:40 UTC, merged