KubeCon EU 2025: Add a ContribFest page (to be merged if we get accepted)
cert-manager/website pull request #1612
Opened 2024-12-10 10:53 UTC by maelvls

**Preview**: https://deploy-preview-1612--cert-manager.netlify.app/announcements/2024/12/10/contribfest-kubecon-eu-2025/

As discussed in https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1733224974283799?thread_ts=1733224600.818759&cid=CDEQJ0Q8M, Richard and I want to submit something to ContribFest at KubeCon EU 2025. The ContribFest will take place on April 2nd, 2024. Feel free to add your name to the list of maintainers if you want to take part.

/hold until the submission gets approved.

For context, here is the list of the previous ContribFest sessions that took place in Salt Lake a month ago: https://kccncna2024.sched.com/overview/type/%F0%9F%9A%A8+Contribfest

**CFP Title:**

🚨 ContribFest: Dive Into cert-manager and Start Contributing!

**CFP Abstract:**

Join us for a hands-on, interactive session with the cert-manager maintainers and community! cert-manager, a graduated CNCF project, automates certificate management for Kubernetes and is a critical component for securing cloud-native applications. This workshop is perfect for both first-time contributors and seasoned open-source enthusiasts. You'll learn about cert-manager's architecture, the role of its key components, and how to set up your environment to start contributing. We’ll walk through the contribution process, tackle curated GitHub issues, and provide guidance tailored to your skill level. Whether you're interested in improving code, documentation, or community engagement, this session offers a great way to make an impact while learning valuable skills. Let’s build cert-manager together!

2024-12-10 11:20 UTC, maelvls commented on content/announcements/2024-12-10-contribfest-kubecon-eu-2025.md
> +- **[#1520](https://github.com/cert-manager/cert-manager/issues/1520)**: Ingress-shim: Skip updating Certificate resource if one already exists.
This is a dump of the first good issues we have at the moment in cert-manager/cert-manager.

They might not be super interesting... If we get accepted, let's work further on curating "actually good" first issues :D

2025-02-03 17:18 UTC, maelvls commented
It was accepted!

2025-02-07 10:43 UTC, SgtCoDFish requested changes
Few suggestions!

2025-02-07 10:43 UTC, SgtCoDFish commented on content/announcements/2024-12-10-contribfest-kubecon-eu-2025.md
> +Stay connected by following us on [Twitter](https://twitter.com/cert_manager), joining the channels `#cert-manager` and `#cert-manager-dev` on the [Kubernetes Slack](https://slack.k8s.io/), and explo
suggestion: Twitter handle looks incorrect, and I'd vote we should link to our slack guide directly rather than repeating it here.

```suggestion
Stay connected by following us on [BlueSky](https://bsky.app/profile/cert-manager.bsky.social), [Mastodon](https://infosec.exchange/@CertManager), [Twitter](https://twitter.com/certmanager), joining us [on Slack](https://cert-manager.io/docs/contributing/#slack), and exploring our [Contributor Guide](https://cert-manager.io/docs/contributing/).
```

2025-02-07 10:43 UTC, SgtCoDFish commented on content/announcements/2024-12-10-contribfest-kubecon-eu-2025.md
> +If you're in London, you can join us for ContribFest on Wednesday, April 2nd, **(details TBD)**.
question: still TBD?

2025-02-07 10:43 UTC, SgtCoDFish commented on content/announcements/2024-12-10-contribfest-kubecon-eu-2025.md
> +date: "2024-12-10T09:00:00Z"
suggestion: might be worth updating this date (and the date in the filename)?

2025-02-11 11:16 UTC, maelvls commented on content/announcements/2024-12-10-contribfest-kubecon-eu-2025.md
> +date: "2024-12-10T09:00:00Z"
Done, thanks.

2025-02-11 11:16 UTC, maelvls commented on content/announcements/2024-12-10-contribfest-kubecon-eu-2025.md
> +If you're in London, you can join us for ContribFest on Wednesday, April 2nd, **(details TBD)**.
Done, thanks.

2025-02-11 13:56 UTC, maelvls commented
I struggled a bit with running `make check` (fixed the bug in https://github.com/cert-manager/website/pull/1644#issue-2845434199), but it should be good to go now.

2025-02-14 11:03 UTC, maelvls commented
Discussed today:

- @hawksight created a spreadsheet with the good first issues: https://docs.google.com/spreadsheets/d/1zThfUB22HHdHAiRvS3ctbj4Da7j30imnUleURjxTYE0/edit?gid=1532279653#gid=1532279653
- @maelvls to propose @wallrj to do the presentation.
- Erik will prepare a devcontainer image.
- Mael will start the tutorial when he comes back on 28th Feb (unless @wallrj wants to start before that). We will decide by then if the devcontainer approach could be used in the tutorial.

2025-02-14 11:39 UTC, maelvls commented on content/announcements/2025-02-11-contribfest-kubecon-eu-2025.md
> +## Good First Issues
List made using 

```bash
gh issue list --repo cert-manager/cert-manager --search 'is:open sort:reactions-+1-desc label:"good first issue"' --json url,title,reactionGroups
```

then given to ChatGPT's o4 with the following prompt:

```
Make a markdown list using the following example:

- **[#6622](https://github.com/cert-manager/cert-manager/issues/6622)**: Improve logging clarity in ACME challenge solver.

Using the following data:
```

Result:

- **[#6269](https://github.com/cert-manager/cert-manager/issues/6269)**: Allow hardcoded JKS and PKCS#12 passwords.
- **[#2334](https://github.com/cert-manager/cert-manager/issues/2334)**: Add network policy allowance into documentation.
- **[#3103](https://github.com/cert-manager/cert-manager/issues/3103)**: Adding probes to the cert-manager pods.
- **[#7184](https://github.com/cert-manager/cert-manager/issues/7184)**: Helm chart: add ability to add appprotocol to port in service.
- **[#7344](https://github.com/cert-manager/cert-manager/issues/7344)**: Support temporary certificates with annotated gateways.
- **[#7459](https://github.com/cert-manager/cert-manager/issues/7459)**: FindZoneByFqdn does not honor SOA TTL.
- **[#7062](https://github.com/cert-manager/cert-manager/issues/7062)**: cainjector shows usages and non json output, if error appears.
- **[#7196](https://github.com/cert-manager/cert-manager/issues/7196)**: cert-manager incorrectly relies only on http status errors to update order error reason.
- **[#7101](https://github.com/cert-manager/cert-manager/issues/7101)**: Add global image repository value to helm values to facilitate private repo and eliminate need to maintain individual repo image paths.

@hawksight

2025-02-14 12:40 UTC, maelvls commented
/unhold since the submission was approved

2025-02-14 12:40 UTC, maelvls commented on content/announcements/2025-02-11-contribfest-kubecon-eu-2025.md
> +TBD
@SgtCoDFish I'll add this part later on.

2025-02-14 12:59 UTC, hawksight commented
Anyone should be able to view the list here: https://docs.google.com/spreadsheets/d/1zThfUB22HHdHAiRvS3ctbj4Da7j30imnUleURjxTYE0/edit?usp=sharing

Would you like me to commit it to this document, in place of the list of items?
I included what you pulled out.

Triage of them is yet to be added.

2025-03-07 18:01 UTC, hawksight commented
@maelvls - I have revised your efforts to generate a CSV we can generate as needed:

My generate.zsh:

```zsh
#!/bin/zsh

repos=(cert-manager trust-manager approver-policy csi-driver csi-driver-spiffe istio-csr base-images google-cas-issuer makefile-modules issuer-lib helm-tool cmctl)
total_count=0
timestamp=$(date -u +%Y%m%d-%H%M%S)
output_file="$timestamp-cert-manager-org-good-first-issues.csv"
header_string="repo,issue_number,url,title,createdAt,updatedAt"

printf "Starting initial file at: $PWD/$output_file\n"
echo '"repo","createdAt","number","title","updatedAt","url"' > $output_file

for repo in ${repos[@]}; do
  issues=$(gh issue list --repo cert-manager/$repo --state open --search 'label:"good first issue"' --json number,url,title,createdAt,updatedAt)
  issue_count=$(echo $issues | jq '. | length')
  total_count=$((total_count + issue_count))
  if [[ $issue_count == 0 ]] ; then
    printf "Skipping repo: cert-manager/$repo as it has $issue_count 'good first' issues...\n"
    continue
  else;
    echo $issues | jq -r '(map(keys) | add | unique) as $cols | map(. as $row | $cols | map($row[.])) as $rows | $cols, $rows[] | @csv'  | awk -v repo=$repo 'NR>1 {print repo","$0}' >> $output_file
    printf "Completed repo: cert-manager/$repo as it has $issue_count 'good first' issues...\n"
  fi

done

printf "Script complete with $total_count 'good first' issues found\n\n"
cat $output_file
printf "\n"
```

An example output:

```log
Starting initial file at: /Users/peter.fiddes/temp/good-first-issues/20250307-175335-cert-manager-org-good-first-issues.csv
Completed repo: cert-manager/cert-manager as it has 6 'good first' issues...
Completed repo: cert-manager/trust-manager as it has 1 'good first' issues...
Completed repo: cert-manager/approver-policy as it has 1 'good first' issues...
Completed repo: cert-manager/csi-driver as it has 1 'good first' issues...
Skipping repo: cert-manager/csi-driver-spiffe as it has 0 'good first' issues...
Skipping repo: cert-manager/istio-csr as it has 0 'good first' issues...
Skipping repo: cert-manager/base-images as it has 0 'good first' issues...
Skipping repo: cert-manager/google-cas-issuer as it has 0 'good first' issues...
Completed repo: cert-manager/makefile-modules as it has 1 'good first' issues...
Skipping repo: cert-manager/issuer-lib as it has 0 'good first' issues...
Skipping repo: cert-manager/helm-tool as it has 0 'good first' issues...
Skipping repo: cert-manager/cmctl as it has 0 'good first' issues...
Script complete with 10 'good first' issues found

"repo","createdAt","number","title","updatedAt","url"
cert-manager,"2024-10-07T11:28:04Z",7344,"Support temporary certificates with annotated gateways","2025-01-13T14:29:58Z","https://github.com/cert-manager/cert-manager/issues/7344"
cert-manager,"2024-07-23T14:35:50Z",7196,"cert-manager incorrectly relies only on http status errors to update order error reason","2025-02-25T11:29:26Z","https://github.com/cert-manager/cert-manager/issues/7196"
cert-manager,"2024-07-18T11:56:41Z",7184,"Helm chart: add ability to add appprotocol to port in service","2025-03-01T22:30:37Z","https://github.com/cert-manager/cert-manager/issues/7184"
cert-manager,"2024-06-03T00:09:39Z",7062,"cainjector shows usages and non json output, if error appears","2024-12-26T13:29:16Z","https://github.com/cert-manager/cert-manager/issues/7062"
cert-manager,"2020-07-17T09:01:17Z",3103,"Adding probes to the cert-manager pods","2025-01-08T12:19:19Z","https://github.com/cert-manager/cert-manager/issues/3103"
cert-manager,"2019-11-08T00:15:03Z",2334,"Add network policy allowance into documentation","2025-02-10T15:36:30Z","https://github.com/cert-manager/cert-manager/issues/2334"
trust-manager,"2022-05-02T04:35:19Z",23,"Way to add labels/annotations to target","2025-02-25T14:37:17Z","https://github.com/cert-manager/trust-manager/issues/23"
approver-policy,"2023-10-04T10:57:46Z",278,"Add Helm option to create RBAC allowing approval for all issuers","2023-10-17T13:25:13Z","https://github.com/cert-manager/approver-policy/issues/278"
csi-driver,"2024-01-09T15:35:03Z",171,"E2E Test Cleanup","2024-01-09T15:35:48Z","https://github.com/cert-manager/csi-driver/issues/171"
makefile-modules,"2024-05-28T14:58:28Z",154,"Publish SBOMs","2024-07-26T11:40:02Z","https://github.com/cert-manager/makefile-modules/issues/154"
```

I have uploaded the results to the same [google sheet](https://docs.google.com/spreadsheets/d/1zThfUB22HHdHAiRvS3ctbj4Da7j30imnUleURjxTYE0/edit?gid=1572423075#gid=1572423075) as before.

Now we just need to triage issues to ensure we have some more "good first issue"'s! Ask you can see there are only 10, across a whole bunch of repos. I will attempt to bring this to standup next week. Maybe Triage party does this for us.. but I hope this is somewhat useful.

Also we need to get this page live, time is ticking.

2025-03-07 18:04 UTC, hawksight commented on content/announcements/2025-02-11-contribfest-kubecon-eu-2025.md
> +TBD
```suggestion
An updated list of open good first issues will be available in [this google sheet](https://docs.google.com/spreadsheets/d/1zThfUB22HHdHAiRvS3ctbj4Da7j30imnUleURjxTYE0/edit?usp=sharing).
```

I don't mind moving the sheet to a cert-manager owned place. Just in my Jetstack google account atm.

2025-03-07 18:05 UTC, hawksight approved these changes
I think we need to get this up, and then we can promote it to people.
Looks good, left a suggestion on issues.

2025-03-07 18:05 UTC, hawksight commented
/lgtm

2025-03-07 18:08 UTC, hawksight commented on content/announcements/2025-02-11-contribfest-kubecon-eu-2025.md
> +date: "2025-02-11T09:00:00Z"
```suggestion
date: "2025-03-10T12:00:00Z"
```

2025-03-11 12:33 UTC, maelvls commented
/approve

2025-03-11 12:34 UTC, merged

2025-03-27 15:14 UTC, maelvls commented
Slides in progress: https://docs.google.com/presentation/d/1yf0troM9crUZFQ3EVT8feZUwfga5OOe0/edit