Prepare v1.1.0 release
cert-manager/website pull request #363
Opened 2020-11-10 09:57 UTC by meyskens

Prepare the release notes + version change for 1.1

2020-11-10 09:58 UTC, meyskens commented
whoops... that's a lot

2020-11-10 10:00 UTC, meyskens commented
FIxed!

2020-11-11 13:41 UTC, wallrj requested changes
I added a paragraph about TPP access-token credentials and spotted a couple of typos.

2020-11-11 13:41 UTC, wallrj commented on content/en/docs/release-notes/release-notes-1.1.md
> +TODO: Richard
```suggestion
It is now possible to use a long lived access-token for authentication when configuring [Venafi TPP Issuer and ClusterIssuer types](https://cert-manager.io/docs/configuration/venafi/).
This authentication mechanism is supported by `Venafi TPP >= 19.2`.
```

2020-11-11 13:41 UTC, wallrj commented on content/en/docs/release-notes/release-notes-1.1.md
> +The ACME issuer is the most used cert-manager issuer. While most use is to talk to Let's Encrypt we are seeing a growing number of new ACME endpoints by certificate authorities,
```suggestion
The ACME issuer is the most used cert-manager issuer. While most use it to talk to Let's Encrypt we are seeing a growing number of new ACME endpoints by certificate authorities,
```

2020-11-11 13:41 UTC, wallrj commented on content/en/docs/release-notes/release-notes-1.1.md
> +This allows you to get more insight into any rate limiting or other errors your ACME issuer provides us.
```suggestion
We improved the recognition and handling of errors given by the ACME server. We are now able to quickly retry transient errors and surface any fatal errors faster in the Kubernetes events and logs.
This allows you to get more insight into any rate limiting or other errors your ACME issuer provides us.
```

2020-11-24 15:49 UTC, wallrj requested changes
[last time we did this](https://github.com/cert-manager/website/pull/309) we also updated:
 *  config/_default/params.toml
 *  scripts/gendocs/generate
 * scripts/update-content
 * scripts/verify-lint

2020-11-24 15:49 UTC, wallrj commented on content/en/docs/installation/kubernetes.md
> +$ kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml
Is it time to remove the `--validate=false` instructions?

2020-11-24 15:49 UTC, wallrj commented on content/en/docs/installation/kubernetes.md
> +$ kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.crds.yaml
Ditto

2020-11-24 15:49 UTC, wallrj commented on content/en/docs/installation/openshift.md
> +oc apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml
```suggestion
oc apply -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml
```

2020-11-24 15:49 UTC, wallrj commented on content/en/docs/installation/openshift.md
> +oc apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml
Hmm, actually, I'm not sure about the `oc` tool. You know more about that than I do.

2020-11-24 15:49 UTC, wallrj commented on content/en/docs/installation/upgrading/_index.md
> +$ kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.crds.yaml
```suggestion
$ kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.crds.yaml
```

2020-11-24 15:49 UTC, wallrj commented on content/en/docs/installation/upgrading/_index.md
> +$ kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml
```suggestion
$ kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml
```

2020-11-24 16:11 UTC, meyskens commented
@wallrj this only adds the release notes not yet switch over the releases to be 1.1 as in the one you referred to

2020-11-24 16:13 UTC, meyskens commented on content/en/docs/installation/kubernetes.md
> +$ kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.crds.yaml
```suggestion
$ kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.crds.yaml
```

2020-11-24 16:13 UTC, meyskens commented on content/en/docs/installation/kubernetes.md
> +$ kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml
```suggestion
$ kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml
```

2020-11-24 16:25 UTC, wallrj approved these changes
/lgtm

2020-11-24 16:36 UTC, merged