Add deprecation notices for old k8s
cert-manager/website pull request #396
Opened 2020-12-22 10:06 UTC by meyskens

Adds upgrade and install notes for 1.2.0 not supporting old kubernetes

2021-01-08 13:50 UTC, wallrj requested changes
Just one small typo and there are a couple of spell check errors to be fixed.

2021-01-08 13:50 UTC, wallrj commented on content/en/docs/installation/upgrading/upgrading-1.1-1.2.md
> +cert-manager `v1.2` will no longer support Kubernetes `v1.15` and below following the Kubernetes upstream version support. We advise you to consider upgrading to Kubernetes 1.16 or above. If this isn
```suggestion
cert-manager `v1.2` will no longer support Kubernetes `v1.15` and below following the Kubernetes upstream version support. We advise you to consider upgrading to Kubernetes 1.16 or above. If this isn't possible we advise you to stay with the cert-manager `v1.1.x` releases.
```

2021-02-05 16:01 UTC, wallrj approved these changes
/lgtm

2021-02-05 16:01 UTC, merged

2021-02-07 17:21 UTC, meyskens commented
This is merged into the wrong branch! It should be reverted!

2021-02-07 17:22 UTC, meyskens commented
/revert