Add deprecation notices for old k8s
cert-manager/website pull request #433
Opened 2021-02-10 18:28 UTC by maelvls

The initial https://github.com/cert-manager/website/pull/396 description from Maartje:

> Adds upgrade and install notes for 1.2.0 not supporting old kubernetes

**Context:** this commit was initially (mistakenly) merged to master in commit 79a7a05b, then reverted in 4828078c. This commit re-introduces the change!

Signed-off-by: Maël Valais <mael@vls.dev>
Co-authored-by: Maartje Eyskens <maartje@eyskens.me>

2021-02-10 18:30 UTC, maelvls commented
@meyskens How do I create the `release-1.2` branch? I don't have any privilege on this repo

2021-02-11 12:09 UTC, wallrj requested changes
Needs a rebase.

2021-02-11 12:24 UTC, irbekrm commented on content/en/docs/installation/kubernetes.md
>    # --set installCRDs=true
Why do we need to comment this out? I imagine some people might fail to read the above sentence (`Uncomment the relevant line in the next steps to enable this.`) and not uncomment it.

2021-02-16 09:19 UTC, jakexks commented
Needs rebase + needs to be into release-next

2021-02-22 21:08 UTC, jakexks commented
/close

2021-02-22 21:08 UTC, closed without merging