Adds approved and denied condition docs
cert-manager/website pull request #502
Opened 2021-04-06 22:32 UTC by JoshVanL

Signed-off-by: joshvanl <vleeuwenjoshua@gmail.com>

Adds docs about:

- The CertificateRequest Approved/Denied conditions, behaviour, and RBAC requirements
- kubectl cert-manager [approve|deny]
- Update the list of external issuers that none of them honour the approval conditions

We should also add an Approver page that lists the projects which implement an approver once [policy-approver](https://github.com/cert-manager/policy-approver) is ready.

2021-04-06 22:40 UTC, JoshVanL commented
Hold for v1.3

/hold

2021-04-08 12:31 UTC, irbekrm requested changes
Looks great to me!

I've added two notes for where it fails spellcheck.

2021-04-08 12:31 UTC, irbekrm commented on content/en/docs/concepts/certificaterequest.md
> +#### Behaviour
This fails spell-check, apparently we prefer US spelling 'Behavior'

2021-04-08 12:31 UTC, irbekrm commented on content/en/docs/concepts/certificaterequest.md
> +Denied condition simultaneously). This behaviour is enforced in the cert-manager
Similarly 'behaviour' -> 'behavior'

2021-04-08 13:36 UTC, irbekrm commented
/approve
/lgtm

2021-04-08 13:45 UTC, JoshVanL commented
/hold cancel

2021-04-08 14:11 UTC, irbekrm commented
/lgtm

2021-04-08 15:24 UTC, JoshVanL commented
@irbekrm Good for another lgtm

2021-04-08 15:33 UTC, irbekrm commented
/lgtm

2021-04-08 15:34 UTC, merged