Certificate signing request ca issuer
cert-manager/website pull request #587
Opened 2021-06-07 08:51 UTC by JoshVanL

2021-06-08 08:45 UTC, maelvls commented
From this morning's discussion: we want to update the website's FAQ to mention that the CSRs are now partially supported in cert-manager.

2021-06-08 17:02 UTC, maelvls commented on content/en/docs/usage/kube-csr.md
> +> Note: cert-manager _will not_ automatically approve CertificateSigningRequests
nit: use present tense instead of future
```suggestion
> Note: cert-manager does not automatically approve CertificateSigningRequests
```

2021-06-08 17:03 UTC, maelvls requested changes
Looks neat. Would it be possible to add a note in the FAQ?

2021-06-09 18:50 UTC, JoshVanL commented
@maelvls Please take another look

2021-06-14 10:30 UTC, maelvls commented
Looks nice and clear, thank you!

/lgtm

2021-06-14 21:03 UTC, maelvls commented
/label cherry-pick-approved

2021-06-14 21:10 UTC, merged