cloud DNS: include missing project ID
cert-manager/website pull request #589
Opened 2021-06-07 19:33 UTC by bpmct

If $PROJECT_ID isn't the default project in `gcloud`, everything works fine except the creation command.

2021-06-08 03:38 UTC, maelvls commented
Good catch! 👍

/ok-to-test

2021-06-08 07:59 UTC, maelvls commented
Looks like the build fails for the same reason as in #588. I'll try to have it fixed and let you know when that's done.

2021-06-16 10:21 UTC, wallrj requested changes

2021-06-16 10:21 UTC, wallrj commented on content/en/docs/configuration/acme/dns01/google.md
> +$ gcloud iam service-accounts create dns01-solver --display-name "dns01-solver --project $PROJECT_ID"
Looks like these quotation marks are in the wrong place. I suggest:

```suggestion
$ gcloud iam service-accounts create dns01-solver --display-name "dns01-solver" --project "${PROJECT_ID}"
```

2023-02-14 09:49 UTC, SgtCoDFish commented
This has been stale for a long time and has a conflict. Gonna close; feel free to re-open or open a new PR!

2023-02-14 09:49 UTC, closed without merging