adding docs for cloud provider tests
cert-manager/website pull request #682
Opened 2021-08-12 06:31 UTC by RinkiyaKeDad

Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>

2021-08-12 08:47 UTC, wallrj commented
/ok-to-test

2021-08-12 12:01 UTC, wallrj requested changes
@RinkiyaKeDad This is a nice addition, thanks.

Just that Jetstack should be capitalized so I changed the hyperlink text in a suggestion below.

2021-08-12 12:42 UTC, wallrj commented on content/en/docs/contributing/e2e.md
> +The master branch of cert-manager can also be tested against different cloud providers. Currently, tests for [EKS](https://aws.amazon.com/eks/) are present which run as a periodic job once every two
Add a TODO / caveat note to explain that the tests do not install cert-manager from the branch-under-test and link to an issue for that.

2021-08-13 11:54 UTC, RinkiyaKeDad commented
@wallrj can you please re-review?

2021-08-13 22:12 UTC, wallrj approved these changes
Nice one Arsh.

Thank you again for all your work on these cloud tests. 

/lgtm
/approve

2021-08-14 08:13 UTC, merged