added multiple azure managed identities documentation
cert-manager/website pull request #688
Opened 2021-08-16 13:18 UTC by tomasfreund

Signed-off-by: Tomáš Freund <tomas.freund@datamole.cz>

Documentation for pull request https://github.com/jetstack/cert-manager/pull/4332

2021-08-20 14:20 UTC, tomasfreund commented
/assign @wallrj

2021-08-25 14:17 UTC, jakexks commented
/ok-to-test

2021-08-25 14:22 UTC, jakexks requested changes
Hi @tomasfreund 

If this is documentation for a feature that will be in 1.6, please could you make this PR against the release-next branch? Anything merged into master is live on the website, which could be confusing for users seeing documentation for a feature that does not yet exist.

2021-08-25 14:23 UTC, jakexks commented on content/en/docs/configuration/acme/dns01/azuredns.md
> +Then when creating the cert-manager issuer we only need to specify the `hostedZoneName`, `resourceGroupName` and `subscriptionID` fields for the DNS Zone.
```suggestion
Then when creating the cert-manager issuer we need to specify the `hostedZoneName`, `resourceGroupName` and `subscriptionID` fields for the DNS Zone.
```

2021-08-31 10:45 UTC, tomasfreund commented
Hi, is there anything more I need to do to get this and https://github.com/jetstack/cert-manager/pull/4332 merged?

2021-09-03 15:16 UTC, wallrj reviewed
Thanks @tomasfreund 

I quoted a couple of words to satisfy the spell-checker and cleaned up some trailing whitespace.

Thanks again for all your work on this.

/lgtm
/approve

2021-09-03 15:25 UTC, merged