Document that DNS-01 ClusterIssuer use kube-system secret
cert-manager/website pull request #765
Opened 2021-11-30 08:59 UTC by MartianGreed

When using a ClusterIssuer with DNS-01 ans route 53, you have to reference a secret that live inside the kube-system namespace

2021-11-30 09:04 UTC, MartianGreed commented
/assign @jakexks

2021-11-30 09:05 UTC, MartianGreed commented
@jakexks this PR is meant to fix this issue [650](https://github.com/jetstack/cert-manager/issues/650)

2021-12-08 09:49 UTC, wallrj requested changes

2021-12-08 09:49 UTC, wallrj commented on content/en/docs/configuration/acme/dns01/route53.md
> +When using a `ClusterIssuer` provided secret have to live inside the `kube-system` namespace so that challenges can properly fetch the secret.
@MartianGreed thanks for raising the issue and apologies for not replying sooner.

Any Secret associated with a ClusterIssuer must reside in the `--cluster-resource-namespace`, 
which is the namespace `cert-manager` by default,
but may be overridden by whoever installed your cert-manager.

See  [Cluster Resource Namespace](https://cert-manager.io/docs/faq/cluster-resource/) and please help us improve that documentation if you have time.

2023-02-08 07:49 UTC, closed without merging