Troubleshoot Helm error when using Azure Issuer
cert-manager/website pull request #857
Opened 2022-02-25 09:08 UTC by MrSimonEmms

Fixes #4867

There's a particularly confusing message when using an Azure Issuer in Helm with the AKS Kubelet identity. This is just something that requires documenting how to get around.

2022-02-25 09:10 UTC, MrSimonEmms commented
I've tried to maintain the style. Happy to make amends with guidance if necessary

2022-03-02 10:23 UTC, irbekrm requested changes
Thank you for this PR, adding this information to the docs was long needed!

I have reworded it to include explanation why `Issuer`s in particular need the flag set + removed Helm reference- let me know if that makes sense, also the comment needs to be moved up to pod identities section I think.

2022-03-02 10:59 UTC, MrSimonEmms commented on content/en/docs/configuration/acme/dns01/azuredns.md
> +
HI @irbekrm, thanks for that. I'll make the changes and resubmit it. I like the new wording as it explains the problem better than I could.

You're right about the other authentication mechanisms not needing this as they don't use ambient credentials.

2022-03-02 11:12 UTC, MrSimonEmms commented
Updated PR to include @irbekrm's suggestion and improved wording. I've changed a couple of stylistic things and a couple of typos from their suggested changed, but mostly imported as-is

2022-03-02 12:04 UTC, irbekrm commented
Thanks for making the changes @MrSimonEmms !

Just one more small nit- can we move this addition to [the pod identities section](https://github.com/cert-manager/website/blob/3ecebce6e09c7cf031396f4b7fcbd7b5ec93dc70/content/en/docs/configuration/acme/dns01/azuredns.md#managed-identity-using-aad-pod-identities) (so around line 136)?
At the moment it has been added to [kubelet identity section](https://cert-manager.io/docs/configuration/acme/dns01/azuredns/#managed-identity-using-aks-kubelet-identity) which should not require ambient credentials flag

2022-03-02 12:09 UTC, MrSimonEmms commented
@irbekrm that's not a nit at all - I'd gone code-blind and put it in the wrong section. Good spot

2022-03-02 12:14 UTC, irbekrm commented
Awesome, this now looks great to me!

Thanks again for taking the initiative to document this bit!

/ok-to-test
/lgtm
/approve

2022-03-02 12:19 UTC, merged