google-season-of-docs: give details on the budget
cert-manager/website pull request #883
Opened 2022-03-25 14:19 UTC by maelvls

cc @wallrj

2022-03-26 17:50 UTC, wallrj requested changes
Thanks @maelvls 

Just one typo to be fixed then can merge.

2022-03-26 17:50 UTC, wallrj commented on content/en/docs/contributing/google-season-of-docs/2022/improve-navigation-and-structure/index.md
> +volonteer can start working. For the stipend to be validated, the PR needs to be reviewed and merged.
```suggestion
We will give the "volunteer stipend" to contributors who can show they have one PR within the project
timeframe (from 1st May to 30th July) in which a re-write of one page or a set of pages. Before
starting the rewriting, the volunteer will suggest which page they wish to work on either on Slack
(Kubernetes Slack, channel #cert-manager-dev), or in an issue on GitHub, and make sure by asking the
team whether it makes sense to rework this page. As long as at least one positive reaction, the
volunteer can start working. For the stipend to be validated, the PR needs to be reviewed and merged.
```

2022-03-28 10:14 UTC, maelvls commented on content/en/docs/contributing/google-season-of-docs/2022/improve-navigation-and-structure/index.md
> +volonteer can start working. For the stipend to be validated, the PR needs to be reviewed and merged.
Done in 653ede2d.

2022-03-29 07:54 UTC, wallrj requested changes
One more spell check error.

```
+++ Running spell check
    content/en/docs/contributing/google-season-of-docs/2022/improve-navigation-and-structure/index.md
       81 | timeframe (from 1st May to 30th July) i 

>> 1 spelling error found in 935 files

```

2022-03-29 07:54 UTC, wallrj commented on content/en/docs/contributing/google-season-of-docs/2022/improve-navigation-and-structure/index.md
> +volunteer can start working. For the stipend to be validated, the PR needs to be reviewed and merged.
```suggestion
We will give the "volunteer stipend" to contributors who can show they have one PR within the project
time frame (from 1st May to 30th July) in which a re-write of one page or a set of pages. Before
starting the rewriting, the volunteer will suggest which page they wish to work on either on Slack
(Kubernetes Slack, channel #cert-manager-dev), or in an issue on GitHub, and make sure by asking the
team whether it makes sense to rework this page. As long as at least one positive reaction, the
volunteer can start working. For the stipend to be validated, the PR needs to be reviewed and merged.
```

2022-03-29 07:57 UTC, maelvls commented on content/en/docs/contributing/google-season-of-docs/2022/improve-navigation-and-structure/index.md
> +volunteer can start working. For the stipend to be validated, the PR needs to be reviewed and merged.
Thanks. Done in b4a9294.

2022-03-29 08:21 UTC, wallrj approved these changes
/lgtm

2022-03-29 08:21 UTC, merged