Update uninstallation instructions
cert-manager/website pull request #927
Opened 2022-04-21 10:12 UTC by enjeck

Closes #559

2022-04-21 10:13 UTC, enjeck commented
@irbekrm I've made changes :)

2022-04-26 10:45 UTC, irbekrm requested changes
Thanks for making the changes @enjeck !

This looks good to me!

I've added a wording suggestion around the owner refs- that part is a little complex, so I'd like to make sure that users understand how it works to minimize the chance of someone accidentally deleting their certs that could result in application downtime and/or unnecessary re-issuances.
Let me know if that makes sense.

2022-04-26 10:45 UTC, irbekrm commented on content/docs/installation/kubectl.md
> +> that owner references are removed.
Suggestion:

You can control the whether owner references are added to `Secret`s using `--enable-certificate-owner-ref` controller flag. By default this flag is set to false, which means that no owner references are added. However, in cert-manager older than v1.8 changing the flag's value from true to false _did not_ result in existing owner references being removed. This behaviour was fixed in cert-manager v1.8.

2022-04-29 17:12 UTC, irbekrm commented
Thanks for working on this @enjeck 

I think the doc looks a lot better now!

/ok-to-test
/lgtm
/approve

2022-05-02 09:51 UTC, maelvls commented
We paired on the failing build this morning, and weren't able to spot where the spelling mistake is. The error is:

```
 +++ Running spell check
    content/docs/installation/kubectl.md
       73 | eferences being removed. This behaviour was fixed in cert-manager v1. 
       73 | our was fixed in cert-manager v1.8. 
>> 2 spelling errors found in 1152 files 
```

I'll try to run the spell checker locally by running

```
./script/verify
```

2022-05-02 10:22 UTC, maelvls commented
I was able to run `./scripts/verify` locally, and it showed the spelling issues in red:

![Screenshot from 2022-05-02 12-17-55](https://user-images.githubusercontent.com/2195781/166219652-68a5c020-31eb-45c0-84da-f4eec73309a8.png)

It seems like `v1.8` is already in `.spelling`, but the spell checker behaves differently when `v1.18` ends with a dot. It doesn't understanding end-of-sentence periods... 😞

**Workaround proposition:** add `v1.8.` to the .spelling file. 😇

> Note: I was struggling during our call due to #957. I just had to run `git cleanup -fd` to fix the "hanging build".

2022-05-02 10:39 UTC, enjeck commented
@maelvls Thank you!

2022-05-05 10:59 UTC, enjeck commented
@maelvls Looks good now. Thank you!

2022-05-05 14:53 UTC, merged