Fix broken links across the site
cert-manager/website pull request #970
Opened 2022-05-05 17:35 UTC by SgtCoDFish

Some of these are relics from before the migration, some happened during the migration. This PR fixes every broken link currently on the site, bumps next-product-docs to fix a bug causing broken links in that tool, and fixes reference docs which were broken in `next-docs`

Everything in this PR was done by hand :sleeping: 

I checked every docs version for broken links using muffet, as here: https://github.com/SgtCoDFish/rutte/blob/7f04ee3c60702661cde4a86bee96d4a0ccd474d3/Makefile#L24-L31

2022-05-05 23:07 UTC, jsoref requested changes
A few changes

2022-05-05 23:07 UTC, jsoref commented on content/v1.8-docs/installation/kubectl.md
> +- Install a [supported version of Kubernetes or OpenShift](../../../docs/installation/supported-releases.md).
This link doesn't seem to work
https://github.com/SgtCoDFish/cert-manager-website/blob/linkslinkslinks/content/v1.8-docs/installation/kubectl.md#prerequisites

This is the file, I think:
https://github.com/SgtCoDFish/cert-manager-website/blob/linkslinkslinks/content/docs/installation/supported-releases.md

```suggestion
- Install a [supported version of Kubernetes or OpenShift](../../docs/installation/supported-releases.md).
```

2022-05-05 23:07 UTC, jsoref commented on content/v1.8-docs/installation/kubectl-plugin.md
> +- Install a [supported version of Kubernetes or OpenShift](../../../docs/installation/supported-releases.md).
See below
```suggestion
- Install a [supported version of Kubernetes or OpenShift](../../docs/installation/supported-releases.md).
```

2022-05-06 10:55 UTC, SgtCoDFish commented on content/v1.8-docs/configuration/acme/dns01/README.md
> +To create a new unsupported DNS provider, follow the development documentation [here](../../../../docs/contributing/dns-providers.md).
Yeah totally fair; hopefully we should have a technical writer taking a look at the site soon, maybe they'll pick up on this kind of thing :+1:

2022-05-06 11:59 UTC, SgtCoDFish commented on content/v1.8-docs/installation/kubectl-plugin.md
> +- Install a [supported version of Kubernetes or OpenShift](../../../docs/installation/supported-releases.md).
Thanks :grin:

2022-05-06 12:34 UTC, wallrj approved these changes
Thanks @SgtCoDFish 

It looks like you've addressed all @jsoref 's remarks and I tested a few of the repaired links and observed that they now work.

I did notice that we no longer have a styled 404 page:
 * https://cert-manager.io/installation/upgrading/upgrading-0.15-0.16/#issue-with-older-versions-of-kubectl/

Is that a known issue?

/lgtm

2022-05-06 12:35 UTC, merged